[project]
name = "intellicleanapp"
version = "0.1.0"
description = "An automated data cleaning and EDA tool built with Streamlit."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "streamlit",
    "pandas",
    "numpy",
    "ydata-profiling",
]